version: '2'
volumes:
    resin-data:
    mqtt-data:
    node-red-data:
services:
    mosquitto:
        build: ./docker-rpi-mosquitto
        image: elzekool/rpi-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - "mqtt-data:/mqtt"
    node-red:
        build: ./resin-node-red
        ports:
            - "80:80"
        volumes:
            - "node-red-data:/data/node-red"
