version: '2'
volumes:
    mosquitto-data:
    mqtt-bridge-data:
services:
    mosquitto:
        build: ./docker-rpi-mosquitto
        image: elzekool/rpi-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - "mosquitto-data:/mqtt"
    mqtt-bridge:
        build: ./docker-mqtt-bridge
        image: stjohnjohnson/smartthings-mqtt-bridge
        volumes:
            - "mqtt-bridge-data:/config"
        ports:
            - "8080:8080"
        links:
            - mosquitto
