version: '2'
volumes:
    resin-data:
services:
    mosquitto:
        build: ./docker-rpi-mosquitto
        image: elzekool/rpi-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - "resin-data/mqtt/data:/mqtt/data"
            - "resin-data/mqtt/log:/mqtt/log"
            - "resin-data/mqtt/config:/mqtt/config"
    node-red:
        build: ./resin-node-red
        ports:
            - "80:80"
        volumes:
            - "resin-data/node-red:/data/node-red"
