version: '2'
volumes:
    mosquitto-data:
    node-red-data:
    mqtt-bridge-data:
    hass-data:
    sonos-api-data:
services:
    mosquitto:
        build: ./docker-rpi-mosquitto
        image: elzekool/rpi-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - "mosquitto-data:/mqtt"
    node-red:
        build: ./resin-node-red
        ports:
            - "8081:8081"
        volumes:
            - "node-red-data:/data/node-red"
        links:
            - mosquitto
    hass:
        image: lroguet/rpi-home-assistant:latest
        network_mode: "host"
        volumes:
            - hass-data:/config
    mqtt-bridge:
        build: ./docker-mqtt-bridge
        image: stjohnjohnson/smartthings-mqtt-bridge
        volumes:
            - "mqtt-bridge-data:/config"
        ports:
            - "8080:8080"
        links:
            - mosquitto
    sono-api:
        build: ./docker-sonos-api
        ports:
            - "80:80"
        volumes:
            - "sonos-api-data:/data"
